### ISSUE TITLE
How Can I open my Vault in Terminal?

### ISSUE THREAD

**Issue by ham1204** [jdluque/obsidian-share-connected-component#1]

**Comment by ham1204** [comment]
Hi, @jdluque 
I'd like to use this, but I don't know how to open the Vault in Terminal_? (mac)
please help.

**Comment by jdluque** [comment]
Open a Terminal and then navigate to your vault's directory by running
```cd /path/to/vault/```
replacing `/path/to/vault/` with the path to your vault. If you're not sure what the path is, have a look at this [link](https://support.apple.com/guide/mac-help/get-file-folder-and-disk-information-on-mac-mchlp1774/mac).
